name: Build aks-desktop (macOS)

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      aks_plugin_branch:
        description: 'Branch to build aks-plugin'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.24.*'

      - name: Setup nodejs
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20.x

      - name: Checkout this repository with submodules
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.inputs.aks_plugin_branch }}
          submodules: recursive

      - name: Setup AKS desktop and Build Headlamp (macOS)
        run: npm run build:mac

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: aks-desktop-mac-dmgs
          path: headlamp/app/dist/aks-desktop*.dmg
